### ISSUE TITLE
Issue after download 

### ISSUE THREAD

**Issue by WeekendFireball** [Mesokrix/Vanilla-Upgraded#9]
Right off the start it says you’re missing a “type “. I’m on mobile and new to modding this so I don’t know if it’s my end or what but I figured I’d put it out there

**Comment by Mesokrix** [comment]
Are you on iOS ?

**Comment by JoanJetson** [comment]
If you are on iOS/iPadOS, that version of Mindystry doesn't support scripts in mods at this time. The mod will load but some functionality won't work since only things fully defined with json files will work. The reason the resource is broken is because the developer has defined some attributes for that resource in a script rather than the json file for that resource.

So you can find out which resource is broken, fork the repo, and add whatever the attribute is missing and use that. Just thought Id give some context that even if the resource issue is resolved, you'll only get partial functionality of the mod.

Do you have the details on which resource it says is missing a type? I can at least point you in the right direction for what the change to make the mod at least load.

**Comment by WeekendFireball** [comment]
That explains every problem I’ve had with mods, but it’s bigheal.hjson

**Comment by Mesokrix** [comment]
Infact bigheal.hjson don't hav the line for the type because the type is define in his script, im really sorry but mods don't work for iOS
